# Form implementation generated from reading ui file 'connect_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_connect_window(object):
    def setupUi(self, connect_window):
        connect_window.setObjectName("connect_window")
        connect_window.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        connect_window.resize(253, 199)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:MSql.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        connect_window.setWindowIcon(icon)
        connect_window.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(connect_window)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=connect_window)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.e_user = QtWidgets.QLineEdit(parent=connect_window)
        self.e_user.setClearButtonEnabled(True)
        self.e_user.setObjectName("e_user")
        self.gridLayout.addWidget(self.e_user, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=connect_window)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.e_password = QtWidgets.QLineEdit(parent=connect_window)
        self.e_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.e_password.setClearButtonEnabled(True)
        self.e_password.setObjectName("e_password")
        self.gridLayout.addWidget(self.e_password, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=connect_window)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.e_tns = QtWidgets.QLineEdit(parent=connect_window)
        self.e_tns.setClearButtonEnabled(True)
        self.e_tns.setObjectName("e_tns")
        self.gridLayout.addWidget(self.e_tns, 2, 2, 1, 1)
        self.e_mode = QtWidgets.QComboBox(parent=connect_window)
        self.e_mode.setObjectName("e_mode")
        self.e_mode.addItem("")
        self.e_mode.addItem("")
        self.gridLayout.addWidget(self.e_mode, 3, 2, 1, 1)
        self.b_connect = QtWidgets.QPushButton(parent=connect_window)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons:connect.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.b_connect.setIcon(icon1)
        self.b_connect.setObjectName("b_connect")
        self.gridLayout.addWidget(self.b_connect, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=connect_window)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 2)
        self.label.setBuddy(self.e_user)
        self.label_2.setBuddy(self.e_password)
        self.label_3.setBuddy(self.e_tns)
        self.label_4.setBuddy(self.e_mode)

        self.retranslateUi(connect_window)
        QtCore.QMetaObject.connectSlotsByName(connect_window)

    def retranslateUi(self, connect_window):
        _translate = QtCore.QCoreApplication.translate
        connect_window.setWindowTitle(_translate("connect_window", "Connect"))
        self.label.setText(_translate("connect_window", "User:"))
        self.label_2.setText(_translate("connect_window", "Password:"))
        self.label_3.setText(_translate("connect_window", "TNS:"))
        self.e_mode.setItemText(0, _translate("connect_window", "Normal"))
        self.e_mode.setItemText(1, _translate("connect_window", "SYSDBA"))
        self.b_connect.setText(_translate("connect_window", "Connect"))
        self.label_4.setText(_translate("connect_window", "Mode:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    connect_window = QtWidgets.QDialog()
    ui = Ui_connect_window()
    ui.setupUi(connect_window)
    connect_window.show()
    sys.exit(app.exec())
