# Form implementation generated from reading ui file 'create_autocomplete_dic_ui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_create_autocomplete_dic_window(object):
    def setupUi(self, create_autocomplete_dic_window):
        create_autocomplete_dic_window.setObjectName("create_autocomplete_dic_window")
        create_autocomplete_dic_window.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        create_autocomplete_dic_window.resize(341, 169)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:MSql.gif"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        create_autocomplete_dic_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=create_autocomplete_dic_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l_schema = QtWidgets.QLabel(parent=self.centralwidget)
        self.l_schema.setObjectName("l_schema")
        self.horizontalLayout.addWidget(self.l_schema)
        self.e_schema = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.e_schema.setEnabled(False)
        self.e_schema.setObjectName("e_schema")
        self.horizontalLayout.addWidget(self.e_schema)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(parent=self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 23, 235, 65))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.e_analyze_1 = QtWidgets.QCheckBox(parent=self.widget)
        self.e_analyze_1.setChecked(True)
        self.e_analyze_1.setObjectName("e_analyze_1")
        self.verticalLayout_2.addWidget(self.e_analyze_1)
        self.e_analyze_2 = QtWidgets.QCheckBox(parent=self.widget)
        self.e_analyze_2.setChecked(True)
        self.e_analyze_2.setObjectName("e_analyze_2")
        self.verticalLayout_2.addWidget(self.e_analyze_2)
        self.e_analyze_3 = QtWidgets.QCheckBox(parent=self.widget)
        self.e_analyze_3.setToolTip("")
        self.e_analyze_3.setChecked(False)
        self.e_analyze_3.setObjectName("e_analyze_3")
        self.verticalLayout_2.addWidget(self.e_analyze_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.b_create = QtWidgets.QPushButton(parent=self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons:dictionary.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.b_create.setIcon(icon1)
        self.b_create.setObjectName("b_create")
        self.verticalLayout.addWidget(self.b_create)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        create_autocomplete_dic_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(create_autocomplete_dic_window)
        self.b_create.clicked.connect(create_autocomplete_dic_window.slot_b_create) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(create_autocomplete_dic_window)
        create_autocomplete_dic_window.setTabOrder(self.e_analyze_1, self.e_analyze_2)
        create_autocomplete_dic_window.setTabOrder(self.e_analyze_2, self.e_analyze_3)
        create_autocomplete_dic_window.setTabOrder(self.e_analyze_3, self.b_create)

    def retranslateUi(self, create_autocomplete_dic_window):
        _translate = QtCore.QCoreApplication.translate
        create_autocomplete_dic_window.setWindowTitle(_translate("create_autocomplete_dic_window", "Create autocomplete dictionary"))
        self.l_schema.setText(_translate("create_autocomplete_dic_window", "Schema that will be analyzed:"))
        self.groupBox.setTitle(_translate("create_autocomplete_dic_window", "Objects selector:"))
        self.e_analyze_1.setText(_translate("create_autocomplete_dic_window", "Analyze function, procedures and packages"))
        self.e_analyze_2.setText(_translate("create_autocomplete_dic_window", "Analyze tables and views"))
        self.e_analyze_3.setText(_translate("create_autocomplete_dic_window", "Analyze Apex objects"))
        self.b_create.setText(_translate("create_autocomplete_dic_window", "Create dictionary"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    create_autocomplete_dic_window = QtWidgets.QMainWindow()
    ui = Ui_create_autocomplete_dic_window()
    ui.setupUi(create_autocomplete_dic_window)
    create_autocomplete_dic_window.show()
    sys.exit(app.exec())
