# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_autocomplete_dic_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_create_autocomplete_dic_window(object):
    def setupUi(self, create_autocomplete_dic_window):
        create_autocomplete_dic_window.setObjectName("create_autocomplete_dic_window")
        create_autocomplete_dic_window.setWindowModality(QtCore.Qt.WindowModal)
        create_autocomplete_dic_window.resize(319, 144)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/MSql.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        create_autocomplete_dic_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(create_autocomplete_dic_window)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 300, 125))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.e_analyze_1 = QtWidgets.QCheckBox(self.groupBox)
        self.e_analyze_1.setChecked(True)
        self.e_analyze_1.setObjectName("e_analyze_1")
        self.verticalLayout.addWidget(self.e_analyze_1)
        self.e_analyze_2 = QtWidgets.QCheckBox(self.groupBox)
        self.e_analyze_2.setChecked(True)
        self.e_analyze_2.setObjectName("e_analyze_2")
        self.verticalLayout.addWidget(self.e_analyze_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.b_create = QtWidgets.QPushButton(self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/dictionary.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_create.setIcon(icon1)
        self.b_create.setObjectName("b_create")
        self.verticalLayout_2.addWidget(self.b_create)
        create_autocomplete_dic_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(create_autocomplete_dic_window)
        self.b_create.clicked.connect(create_autocomplete_dic_window.slot_b_create) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(create_autocomplete_dic_window)
        create_autocomplete_dic_window.setTabOrder(self.e_analyze_1, self.e_analyze_2)
        create_autocomplete_dic_window.setTabOrder(self.e_analyze_2, self.b_create)

    def retranslateUi(self, create_autocomplete_dic_window):
        _translate = QtCore.QCoreApplication.translate
        create_autocomplete_dic_window.setWindowTitle(_translate("create_autocomplete_dic_window", "Create autocomplete dictionary"))
        self.groupBox.setTitle(_translate("create_autocomplete_dic_window", "Objects selector:"))
        self.e_analyze_1.setText(_translate("create_autocomplete_dic_window", "Analyze function, procedures and packages"))
        self.e_analyze_2.setText(_translate("create_autocomplete_dic_window", "Analyze tables and views"))
        self.b_create.setText(_translate("create_autocomplete_dic_window", "Create dictionary"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    create_autocomplete_dic_window = QtWidgets.QMainWindow()
    ui = Ui_create_autocomplete_dic_window()
    ui.setupUi(create_autocomplete_dic_window)
    create_autocomplete_dic_window.show()
    sys.exit(app.exec_())
