# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'find_e_replace_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Find_e_Replace_Window(object):
    def setupUi(self, Find_e_Replace_Window):
        Find_e_Replace_Window.setObjectName("Find_e_Replace_Window")
        Find_e_Replace_Window.resize(259, 180)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/replace.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Find_e_Replace_Window.setWindowIcon(icon)
        self.formLayout = QtWidgets.QFormLayout(Find_e_Replace_Window)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Find_e_Replace_Window)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.e_find = QtWidgets.QComboBox(Find_e_Replace_Window)
        self.e_find.setEditable(True)
        self.e_find.setObjectName("e_find")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.e_find)
        self.label_2 = QtWidgets.QLabel(Find_e_Replace_Window)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.e_replace = QtWidgets.QComboBox(Find_e_Replace_Window)
        self.e_replace.setEditable(True)
        self.e_replace.setObjectName("e_replace")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.e_replace)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.b_find_next = QtWidgets.QPushButton(Find_e_Replace_Window)
        self.b_find_next.setObjectName("b_find_next")
        self.verticalLayout.addWidget(self.b_find_next)
        self.b_replace_next = QtWidgets.QPushButton(Find_e_Replace_Window)
        self.b_replace_next.setObjectName("b_replace_next")
        self.verticalLayout.addWidget(self.b_replace_next)
        self.b_replace_all = QtWidgets.QPushButton(Find_e_Replace_Window)
        self.b_replace_all.setObjectName("b_replace_all")
        self.verticalLayout.addWidget(self.b_replace_all)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.label.setBuddy(self.e_find)
        self.label_2.setBuddy(self.e_replace)

        self.retranslateUi(Find_e_Replace_Window)
        QtCore.QMetaObject.connectSlotsByName(Find_e_Replace_Window)
        Find_e_Replace_Window.setTabOrder(self.e_find, self.e_replace)
        Find_e_Replace_Window.setTabOrder(self.e_replace, self.b_find_next)
        Find_e_Replace_Window.setTabOrder(self.b_find_next, self.b_replace_next)
        Find_e_Replace_Window.setTabOrder(self.b_replace_next, self.b_replace_all)

    def retranslateUi(self, Find_e_Replace_Window):
        _translate = QtCore.QCoreApplication.translate
        Find_e_Replace_Window.setWindowTitle(_translate("Find_e_Replace_Window", "Find and Replace"))
        self.label.setText(_translate("Find_e_Replace_Window", "Text to find:"))
        self.label_2.setText(_translate("Find_e_Replace_Window", "Text to replace:"))
        self.b_find_next.setText(_translate("Find_e_Replace_Window", "Find next"))
        self.b_replace_next.setText(_translate("Find_e_Replace_Window", "Replace"))
        self.b_replace_all.setText(_translate("Find_e_Replace_Window", "Replace all"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Find_e_Replace_Window = QtWidgets.QDialog()
    ui = Ui_Find_e_Replace_Window()
    ui.setupUi(Find_e_Replace_Window)
    Find_e_Replace_Window.show()
    sys.exit(app.exec_())
