# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'find_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FindWindow(object):
    def setupUi(self, FindWindow):
        FindWindow.setObjectName("FindWindow")
        FindWindow.resize(259, 325)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/search_file.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FindWindow.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(FindWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.e_find = QtWidgets.QComboBox(FindWindow)
        self.e_find.setEditable(True)
        self.e_find.setObjectName("e_find")
        self.gridLayout.addWidget(self.e_find, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(FindWindow)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b_next = QtWidgets.QPushButton(FindWindow)
        self.b_next.setObjectName("b_next")
        self.horizontalLayout.addWidget(self.b_next)
        self.b_find_all = QtWidgets.QPushButton(FindWindow)
        self.b_find_all.setObjectName("b_find_all")
        self.horizontalLayout.addWidget(self.b_find_all)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(FindWindow)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.o_find_all_result = QtWidgets.QListView(FindWindow)
        self.o_find_all_result.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.o_find_all_result.setAlternatingRowColors(True)
        self.o_find_all_result.setObjectName("o_find_all_result")
        self.verticalLayout.addWidget(self.o_find_all_result)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.label.setBuddy(self.e_find)

        self.retranslateUi(FindWindow)
        QtCore.QMetaObject.connectSlotsByName(FindWindow)
        FindWindow.setTabOrder(self.e_find, self.b_next)
        FindWindow.setTabOrder(self.b_next, self.b_find_all)
        FindWindow.setTabOrder(self.b_find_all, self.o_find_all_result)

    def retranslateUi(self, FindWindow):
        _translate = QtCore.QCoreApplication.translate
        FindWindow.setWindowTitle(_translate("FindWindow", "Find"))
        self.label.setText(_translate("FindWindow", "Text to find:"))
        self.b_next.setText(_translate("FindWindow", "Find next (F3)"))
        self.b_next.setShortcut(_translate("FindWindow", "F3"))
        self.b_find_all.setText(_translate("FindWindow", "Find all"))
        self.label_2.setText(_translate("FindWindow", "Search result:"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FindWindow = QtWidgets.QDialog()
    ui = Ui_FindWindow()
    ui.setupUi(FindWindow)
    FindWindow.show()
    sys.exit(app.exec_())
