# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'goto_line_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GotoLineWindow(object):
    def setupUi(self, GotoLineWindow):
        GotoLineWindow.setObjectName("GotoLineWindow")
        GotoLineWindow.resize(382, 51)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/right.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GotoLineWindow.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(GotoLineWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(GotoLineWindow)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.b_goto_line = QtWidgets.QPushButton(GotoLineWindow)
        self.b_goto_line.setText("")
        self.b_goto_line.setIcon(icon)
        self.b_goto_line.setObjectName("b_goto_line")
        self.gridLayout.addWidget(self.b_goto_line, 0, 2, 1, 1)
        self.e_goto_line = QtWidgets.QComboBox(GotoLineWindow)
        self.e_goto_line.setEditable(True)
        self.e_goto_line.setObjectName("e_goto_line")
        self.gridLayout.addWidget(self.e_goto_line, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.label.setBuddy(self.e_goto_line)

        self.retranslateUi(GotoLineWindow)
        QtCore.QMetaObject.connectSlotsByName(GotoLineWindow)
        GotoLineWindow.setTabOrder(self.e_goto_line, self.b_goto_line)

    def retranslateUi(self, GotoLineWindow):
        _translate = QtCore.QCoreApplication.translate
        GotoLineWindow.setWindowTitle(_translate("GotoLineWindow", "Go To Line"))
        self.label.setText(_translate("GotoLineWindow", "Enter line number:"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GotoLineWindow = QtWidgets.QDialog()
    ui = Ui_GotoLineWindow()
    ui.setupUi(GotoLineWindow)
    GotoLineWindow.show()
    sys.exit(app.exec_())
