# Form implementation generated from reading ui file 'history_ui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_history_window(object):
    def setupUi(self, history_window):
        history_window.setObjectName("history_window")
        history_window.resize(735, 776)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:MSql.gif"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        history_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=history_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.o_lst1 = QtWidgets.QTableView(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.o_lst1.setFont(font)
        self.o_lst1.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.o_lst1.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.o_lst1.setObjectName("o_lst1")
        self.gridLayout.addWidget(self.o_lst1, 2, 0, 1, 1)
        self.b_purge = QtWidgets.QPushButton(parent=self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons:failed.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.b_purge.setIcon(icon1)
        self.b_purge.setObjectName("b_purge")
        self.gridLayout.addWidget(self.b_purge, 1, 0, 1, 1)
        self.b_insert_in_editor = QtWidgets.QPushButton(parent=self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons:indent.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.b_insert_in_editor.setIcon(icon2)
        self.b_insert_in_editor.setObjectName("b_insert_in_editor")
        self.gridLayout.addWidget(self.b_insert_in_editor, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l_label6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.l_label6.setObjectName("l_label6")
        self.horizontalLayout.addWidget(self.l_label6)
        self.e_where_cond = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.e_where_cond.setObjectName("e_where_cond")
        self.horizontalLayout.addWidget(self.e_where_cond)
        self.b_start = QtWidgets.QPushButton(parent=self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons:go.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.b_start.setIcon(icon3)
        self.b_start.setObjectName("b_start")
        self.horizontalLayout.addWidget(self.b_start)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        history_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(history_window)
        self.b_start.clicked.connect(history_window.slot_start) # type: ignore
        self.b_purge.clicked.connect(history_window.slot_purge) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(history_window)
        history_window.setTabOrder(self.e_where_cond, self.b_start)
        history_window.setTabOrder(self.b_start, self.b_purge)
        history_window.setTabOrder(self.b_purge, self.o_lst1)
        history_window.setTabOrder(self.o_lst1, self.b_insert_in_editor)

    def retranslateUi(self, history_window):
        _translate = QtCore.QCoreApplication.translate
        history_window.setWindowTitle(_translate("history_window", "History"))
        self.b_purge.setText(_translate("history_window", "Delete history"))
        self.b_insert_in_editor.setText(_translate("history_window", "Insert SQL in editor"))
        self.l_label6.setText(_translate("history_window", "Text to find"))
        self.b_start.setText(_translate("history_window", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    history_window = QtWidgets.QMainWindow()
    ui = Ui_history_window()
    ui.setupUi(history_window)
    history_window.show()
    sys.exit(app.exec())
