# Form implementation generated from reading ui file 'import_export_excel_to_oracle_ui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_import_export_window(object):
    def setupUi(self, import_export_window):
        import_export_window.setObjectName("import_export_window")
        import_export_window.resize(304, 124)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:MSql.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        import_export_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=import_export_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.e_table_name = QtWidgets.QComboBox(parent=self.centralwidget)
        self.e_table_name.setEditable(True)
        self.e_table_name.setMaxVisibleItems(20)
        self.e_table_name.setObjectName("e_table_name")
        self.gridLayout.addWidget(self.e_table_name, 2, 1, 1, 2)
        self.l_label2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.l_label2.setObjectName("l_label2")
        self.gridLayout.addWidget(self.l_label2, 0, 0, 1, 1)
        self.l_label5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.l_label5.setObjectName("l_label5")
        self.gridLayout.addWidget(self.l_label5, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.e_excel = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.e_excel.setClearButtonEnabled(True)
        self.e_excel.setObjectName("e_excel")
        self.horizontalLayout.addWidget(self.e_excel)
        self.b_excel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.b_excel.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons:folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.b_excel.setIcon(icon1)
        self.b_excel.setObjectName("b_excel")
        self.horizontalLayout.addWidget(self.b_excel)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 2)
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 3)
        self.b_start = QtWidgets.QPushButton(parent=self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons:go.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.b_start.setIcon(icon2)
        self.b_start.setObjectName("b_start")
        self.gridLayout.addWidget(self.b_start, 4, 1, 1, 2)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 3)
        import_export_window.setCentralWidget(self.centralwidget)
        self.l_label2.setBuddy(self.e_excel)
        self.l_label5.setBuddy(self.e_table_name)

        self.retranslateUi(import_export_window)
        self.b_excel.clicked.connect(import_export_window.slot_select_excel_file) # type: ignore
        self.b_start.clicked.connect(import_export_window.slot_start) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(import_export_window)
        import_export_window.setTabOrder(self.e_excel, self.b_excel)
        import_export_window.setTabOrder(self.b_excel, self.e_table_name)
        import_export_window.setTabOrder(self.e_table_name, self.b_start)

    def retranslateUi(self, import_export_window):
        _translate = QtCore.QCoreApplication.translate
        import_export_window.setWindowTitle(_translate("import_export_window", "Copy data from Excel to Oracle"))
        self.l_label2.setText(_translate("import_export_window", "Excel file:"))
        self.l_label5.setText(_translate("import_export_window", "Oracle table name:"))
        self.b_start.setText(_translate("import_export_window", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    import_export_window = QtWidgets.QMainWindow()
    ui = Ui_import_export_window()
    ui.setupUi(import_export_window)
    import_export_window.show()
    sys.exit(app.exec())
