# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MSql_editor_win3_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MSql_win3(object):
    def setupUi(self, MSql_win3):
        MSql_win3.setObjectName("MSql_win3")
        MSql_win3.resize(684, 332)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/MSql.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MSql_win3.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(MSql_win3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(MSql_win3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(MSql_win3)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(MSql_win3)
        QtCore.QMetaObject.connectSlotsByName(MSql_win3)

    def retranslateUi(self, MSql_win3):
        _translate = QtCore.QCoreApplication.translate
        MSql_win3.setWindowTitle(_translate("MSql_win3", "About MSql Editor"))
        self.label.setText(_translate("MSql_win3", "<html><head/><body><p align=\"center\"><img src=\":/icons/icons/MSql.ico\"/></p><p align=\"center\"><img src=\":/icons/icons/python.gif\"/><img src=\":/icons/icons/qt.gif\"/></p><p align=\"center\"><img src=\":/icons/icons/SciTEIco.gif\"/></p></body></html>"))
        self.label_2.setText(_translate("MSql_win3", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">MSql Editor </span><span style=\" font-size:10pt;\">© 2023-2024</span></p><p align=\"center\"><span style=\" font-size:10pt;\">MSql Editor is a SQL text editor for oracle environment.</span></p><p align=\"center\"><span style=\" font-size:10pt;\">Developed by </span><span style=\" font-size:10pt; font-weight:600;\">Marco Valaguzza</span></p><p align=\"center\"><span style=\" font-size:10pt;\">with Python 3.11, QT library 5 and Scintilla</span></p><p align=\"center\"><span style=\" font-size:10pt;\"><br/></span></p></body></html>"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MSql_win3 = QtWidgets.QDialog()
    ui = Ui_MSql_win3()
    ui.setupUi(MSql_win3)
    MSql_win3.show()
    sys.exit(app.exec_())
