# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MSql_editor_win2_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MSql_win2(object):
    def setupUi(self, MSql_win2):
        MSql_win2.setObjectName("MSql_win2")
        MSql_win2.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/MSql.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MSql_win2.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MSql_win2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(7, 7, 7, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.e_sql = Qsci.QsciScintilla(self.splitter)
        self.e_sql.setMinimumSize(QtCore.QSize(0, 100))
        self.e_sql.setObjectName("e_sql")
        self.o_tab_widget = QtWidgets.QTabWidget(self.splitter)
        self.o_tab_widget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.o_tab_widget.setObjectName("o_tab_widget")
        self.t_result = QtWidgets.QWidget()
        self.t_result.setObjectName("t_result")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.t_result)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.o_table = QtWidgets.QTableWidget(self.t_result)
        self.o_table.setAlternatingRowColors(True)
        self.o_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.o_table.setGridStyle(QtCore.Qt.SolidLine)
        self.o_table.setObjectName("o_table")
        self.o_table.setColumnCount(0)
        self.o_table.setRowCount(0)
        self.verticalLayout_2.addWidget(self.o_table)
        self.o_tab_widget.addTab(self.t_result, "")
        self.t_output = QtWidgets.QWidget()
        self.t_output.setObjectName("t_output")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.t_output)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.o_output = QtWidgets.QPlainTextEdit(self.t_output)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.o_output.setFont(font)
        self.o_output.setReadOnly(True)
        self.o_output.setObjectName("o_output")
        self.verticalLayout_3.addWidget(self.o_output)
        self.o_tab_widget.addTab(self.t_output, "")
        self.verticalLayout.addWidget(self.splitter)
        MSql_win2.setCentralWidget(self.centralwidget)

        self.retranslateUi(MSql_win2)
        self.o_tab_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MSql_win2)

    def retranslateUi(self, MSql_win2):
        _translate = QtCore.QCoreApplication.translate
        self.o_tab_widget.setTabText(self.o_tab_widget.indexOf(self.t_result), _translate("MSql_win2", "Result"))
        self.o_tab_widget.setTabText(self.o_tab_widget.indexOf(self.t_output), _translate("MSql_win2", "Output"))
from PyQt5 import Qsci
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MSql_win2 = QtWidgets.QMainWindow()
    ui = Ui_MSql_win2()
    ui.setupUi(MSql_win2)
    MSql_win2.show()
    sys.exit(app.exec_())
