# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MSql_editor_win2_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MSql_win2(object):
    def setupUi(self, MSql_win2):
        MSql_win2.setObjectName("MSql_win2")
        MSql_win2.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MSql_win2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(7, -1, 7, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.splitter_obj = QtWidgets.QSplitter(self.splitter)
        self.splitter_obj.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_obj.setObjectName("splitter_obj")
        self.e_sql = code_editor(self.splitter_obj)
        self.e_sql.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(11)
        self.e_sql.setFont(font)
        self.e_sql.setObjectName("e_sql")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_obj)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.oggetti_db_scelta = QtWidgets.QComboBox(self.layoutWidget)
        self.oggetti_db_scelta.setObjectName("oggetti_db_scelta")
        self.oggetti_db_scelta.addItem("")
        self.oggetti_db_scelta.setItemText(0, "")
        self.oggetti_db_scelta.addItem("")
        self.oggetti_db_scelta.addItem("")
        self.oggetti_db_scelta.addItem("")
        self.oggetti_db_scelta.addItem("")
        self.oggetti_db_scelta.addItem("")
        self.oggetti_db_scelta.addItem("")
        self.verticalLayout.addWidget(self.oggetti_db_scelta)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.oggetti_db_tipo_ricerca = QtWidgets.QComboBox(self.layoutWidget)
        self.oggetti_db_tipo_ricerca.setObjectName("oggetti_db_tipo_ricerca")
        self.oggetti_db_tipo_ricerca.addItem("")
        self.oggetti_db_tipo_ricerca.addItem("")
        self.horizontalLayout.addWidget(self.oggetti_db_tipo_ricerca)
        self.oggetti_db_ricerca = QtWidgets.QLineEdit(self.layoutWidget)
        self.oggetti_db_ricerca.setInputMethodHints(QtCore.Qt.ImhNone)
        self.oggetti_db_ricerca.setObjectName("oggetti_db_ricerca")
        self.horizontalLayout.addWidget(self.oggetti_db_ricerca)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.oggetti_db_elenco = QtWidgets.QListView(self.layoutWidget)
        self.oggetti_db_elenco.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.oggetti_db_elenco.setDragEnabled(True)
        self.oggetti_db_elenco.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.oggetti_db_elenco.setAlternatingRowColors(True)
        self.oggetti_db_elenco.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.oggetti_db_elenco.setObjectName("oggetti_db_elenco")
        self.verticalLayout.addWidget(self.oggetti_db_elenco)
        self.o_tab_widget = QtWidgets.QTabWidget(self.splitter)
        self.o_tab_widget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.o_tab_widget.setObjectName("o_tab_widget")
        self.t_result = QtWidgets.QWidget()
        self.t_result.setObjectName("t_result")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.t_result)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.o_table = QtWidgets.QTableWidget(self.t_result)
        self.o_table.setAlternatingRowColors(True)
        self.o_table.setGridStyle(QtCore.Qt.SolidLine)
        self.o_table.setObjectName("o_table")
        self.o_table.setColumnCount(0)
        self.o_table.setRowCount(0)
        self.o_table.horizontalHeader().setSortIndicatorShown(True)
        self.verticalLayout_2.addWidget(self.o_table)
        self.o_tab_widget.addTab(self.t_result, "")
        self.t_output = QtWidgets.QWidget()
        self.t_output.setObjectName("t_output")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.t_output)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.o_output = QtWidgets.QPlainTextEdit(self.t_output)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.o_output.setFont(font)
        self.o_output.setReadOnly(True)
        self.o_output.setObjectName("o_output")
        self.verticalLayout_3.addWidget(self.o_output)
        self.o_tab_widget.addTab(self.t_output, "")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MSql_win2.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MSql_win2)
        self.statusBar.setObjectName("statusBar")
        MSql_win2.setStatusBar(self.statusBar)

        self.retranslateUi(MSql_win2)
        self.o_tab_widget.setCurrentIndex(1)
        self.oggetti_db_scelta.currentTextChanged['QString'].connect(MSql_win2.slot_oggetti_db_scelta) # type: ignore
        self.oggetti_db_tipo_ricerca.currentTextChanged['QString'].connect(MSql_win2.slot_oggetti_db_scelta) # type: ignore
        self.oggetti_db_ricerca.editingFinished.connect(MSql_win2.slot_oggetti_db_scelta) # type: ignore
        self.oggetti_db_elenco.doubleClicked['QModelIndex'].connect(MSql_win2.slot_oggetti_db_doppio_click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MSql_win2)

    def retranslateUi(self, MSql_win2):
        _translate = QtCore.QCoreApplication.translate
        self.oggetti_db_scelta.setItemText(1, _translate("MSql_win2", "Tables"))
        self.oggetti_db_scelta.setItemText(2, _translate("MSql_win2", "Package"))
        self.oggetti_db_scelta.setItemText(3, _translate("MSql_win2", "Trigger"))
        self.oggetti_db_scelta.setItemText(4, _translate("MSql_win2", "Procedures"))
        self.oggetti_db_scelta.setItemText(5, _translate("MSql_win2", "Functions"))
        self.oggetti_db_scelta.setItemText(6, _translate("MSql_win2", "Views"))
        self.oggetti_db_tipo_ricerca.setItemText(0, _translate("MSql_win2", "Start with"))
        self.oggetti_db_tipo_ricerca.setItemText(1, _translate("MSql_win2", "Like"))
        self.o_table.setSortingEnabled(True)
        self.o_tab_widget.setTabText(self.o_tab_widget.indexOf(self.t_result), _translate("MSql_win2", "Result"))
        self.o_tab_widget.setTabText(self.o_tab_widget.indexOf(self.t_output), _translate("MSql_win2", "Output"))
from code_editor import code_editor
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MSql_win2 = QtWidgets.QMainWindow()
    ui = Ui_MSql_win2()
    ui.setupUi(MSql_win2)
    MSql_win2.show()
    sys.exit(app.exec_())
