# Form implementation generated from reading ui file 'object_info_ui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_object_info_window(object):
    def setupUi(self, object_info_window):
        object_info_window.setObjectName("object_info_window")
        object_info_window.resize(302, 197)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:MSql.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        object_info_window.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(object_info_window)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=object_info_window)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.e_object_name = QtWidgets.QLineEdit(parent=object_info_window)
        self.e_object_name.setReadOnly(True)
        self.e_object_name.setObjectName("e_object_name")
        self.gridLayout.addWidget(self.e_object_name, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=object_info_window)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.e_owner = QtWidgets.QLineEdit(parent=object_info_window)
        self.e_owner.setReadOnly(True)
        self.e_owner.setObjectName("e_owner")
        self.gridLayout.addWidget(self.e_owner, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=object_info_window)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.e_object_type = QtWidgets.QLineEdit(parent=object_info_window)
        self.e_object_type.setReadOnly(True)
        self.e_object_type.setObjectName("e_object_type")
        self.gridLayout.addWidget(self.e_object_type, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=object_info_window)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.e_created = QtWidgets.QLineEdit(parent=object_info_window)
        self.e_created.setReadOnly(True)
        self.e_created.setObjectName("e_created")
        self.gridLayout.addWidget(self.e_created, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=object_info_window)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.e_modified = QtWidgets.QLineEdit(parent=object_info_window)
        self.e_modified.setReadOnly(True)
        self.e_modified.setObjectName("e_modified")
        self.gridLayout.addWidget(self.e_modified, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=object_info_window)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.e_status = QtWidgets.QLineEdit(parent=object_info_window)
        self.e_status.setReadOnly(True)
        self.e_status.setObjectName("e_status")
        self.gridLayout.addWidget(self.e_status, 5, 1, 1, 1)

        self.retranslateUi(object_info_window)
        QtCore.QMetaObject.connectSlotsByName(object_info_window)

    def retranslateUi(self, object_info_window):
        _translate = QtCore.QCoreApplication.translate
        object_info_window.setWindowTitle(_translate("object_info_window", "Object info"))
        self.label.setText(_translate("object_info_window", "Object name"))
        self.label_2.setText(_translate("object_info_window", "Owner"))
        self.label_3.setText(_translate("object_info_window", "Object type"))
        self.label_4.setText(_translate("object_info_window", "Created"))
        self.label_5.setText(_translate("object_info_window", "Modified"))
        self.label_6.setText(_translate("object_info_window", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    object_info_window = QtWidgets.QDialog()
    ui = Ui_object_info_window()
    ui.setupUi(object_info_window)
    object_info_window.show()
    sys.exit(app.exec())
