# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferred_sql_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_preferred_sql_window(object):
    def setupUi(self, preferred_sql_window):
        preferred_sql_window.setObjectName("preferred_sql_window")
        preferred_sql_window.resize(676, 691)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/MSql.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        preferred_sql_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(preferred_sql_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l_label6 = QtWidgets.QLabel(self.centralwidget)
        self.l_label6.setObjectName("l_label6")
        self.horizontalLayout.addWidget(self.l_label6)
        self.e_where_cond = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_where_cond.sizePolicy().hasHeightForWidth())
        self.e_where_cond.setSizePolicy(sizePolicy)
        self.e_where_cond.setMaximumSize(QtCore.QSize(16777215, 50))
        self.e_where_cond.setObjectName("e_where_cond")
        self.horizontalLayout.addWidget(self.e_where_cond)
        self.b_start = QtWidgets.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/go.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_start.setIcon(icon1)
        self.b_start.setObjectName("b_start")
        self.horizontalLayout.addWidget(self.b_start)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.b_insert_row = QtWidgets.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_insert_row.setIcon(icon2)
        self.b_insert_row.setObjectName("b_insert_row")
        self.horizontalLayout_2.addWidget(self.b_insert_row)
        self.b_delete_row = QtWidgets.QPushButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/failed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_delete_row.setIcon(icon3)
        self.b_delete_row.setObjectName("b_delete_row")
        self.horizontalLayout_2.addWidget(self.b_delete_row)
        self.b_debug = QtWidgets.QPushButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/debug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_debug.setIcon(icon4)
        self.b_debug.setObjectName("b_debug")
        self.horizontalLayout_2.addWidget(self.b_debug)
        self.b_save_rows = QtWidgets.QPushButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_save_rows.setIcon(icon5)
        self.b_save_rows.setObjectName("b_save_rows")
        self.horizontalLayout_2.addWidget(self.b_save_rows)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.o_tabella = QtWidgets.QTableWidget(self.centralwidget)
        self.o_tabella.setObjectName("o_tabella")
        self.o_tabella.setColumnCount(0)
        self.o_tabella.setRowCount(0)
        self.gridLayout.addWidget(self.o_tabella, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b_insert_in_editor = QtWidgets.QPushButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/indent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_insert_in_editor.setIcon(icon6)
        self.b_insert_in_editor.setObjectName("b_insert_in_editor")
        self.horizontalLayout_3.addWidget(self.b_insert_in_editor)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        preferred_sql_window.setCentralWidget(self.centralwidget)
        self.l_label6.setBuddy(self.e_where_cond)

        self.retranslateUi(preferred_sql_window)
        self.b_start.clicked.connect(preferred_sql_window.slot_start) # type: ignore
        self.b_insert_row.clicked.connect(preferred_sql_window.slot_insert_row) # type: ignore
        self.b_delete_row.clicked.connect(preferred_sql_window.slot_delete_row) # type: ignore
        self.b_save_rows.clicked.connect(preferred_sql_window.slot_save) # type: ignore
        self.o_tabella.cellChanged['int','int'].connect(preferred_sql_window.slot_cell_changed) # type: ignore
        self.b_debug.clicked.connect(preferred_sql_window.slot_debug) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(preferred_sql_window)
        preferred_sql_window.setTabOrder(self.e_where_cond, self.b_start)
        preferred_sql_window.setTabOrder(self.b_start, self.b_insert_row)
        preferred_sql_window.setTabOrder(self.b_insert_row, self.b_delete_row)
        preferred_sql_window.setTabOrder(self.b_delete_row, self.b_debug)
        preferred_sql_window.setTabOrder(self.b_debug, self.b_save_rows)
        preferred_sql_window.setTabOrder(self.b_save_rows, self.o_tabella)
        preferred_sql_window.setTabOrder(self.o_tabella, self.b_insert_in_editor)

    def retranslateUi(self, preferred_sql_window):
        _translate = QtCore.QCoreApplication.translate
        preferred_sql_window.setWindowTitle(_translate("preferred_sql_window", "Preferred SQL"))
        self.l_label6.setText(_translate("preferred_sql_window", "Where condition (ex. SQL like \'%VALUE%\'):"))
        self.b_start.setText(_translate("preferred_sql_window", "Search"))
        self.b_insert_row.setText(_translate("preferred_sql_window", "Insert row"))
        self.b_delete_row.setText(_translate("preferred_sql_window", "Delete row"))
        self.b_debug.setText(_translate("preferred_sql_window", "Debug"))
        self.b_save_rows.setText(_translate("preferred_sql_window", "Save"))
        self.o_tabella.setSortingEnabled(True)
        self.b_insert_in_editor.setText(_translate("preferred_sql_window", "Insert SQL in editor"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    preferred_sql_window = QtWidgets.QMainWindow()
    ui = Ui_preferred_sql_window()
    ui.setupUi(preferred_sql_window)
    preferred_sql_window.show()
    sys.exit(app.exec_())
