# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'program_info_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_program_info(object):
    def setupUi(self, program_info):
        program_info.setObjectName("program_info")
        program_info.resize(684, 332)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/MSql.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        program_info.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(program_info)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(program_info)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(program_info)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(program_info)
        QtCore.QMetaObject.connectSlotsByName(program_info)

    def retranslateUi(self, program_info):
        _translate = QtCore.QCoreApplication.translate
        program_info.setWindowTitle(_translate("program_info", "About MSql Editor"))
        self.label.setText(_translate("program_info", "<html><head/><body><p align=\"center\"><img src=\":/icons/icons/MSql.ico\"/></p><p align=\"center\"><img src=\":/icons/icons/python.gif\"/><img src=\":/icons/icons/qt.gif\"/></p><p align=\"center\"><img src=\":/icons/icons/SciTEIco.gif\"/></p></body></html>"))
        self.label_2.setText(_translate("program_info", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">MSql Editor </span><span style=\" font-size:10pt;\">© 2023-2024</span></p><p align=\"center\"><span style=\" font-size:10pt;\">MSql Editor is a SQL text editor for oracle environment.</span></p><p align=\"center\"><span style=\" font-size:10pt;\">Developed by </span><span style=\" font-size:10pt; font-weight:600;\">Marco Valaguzza</span></p><p align=\"center\"><span style=\" font-size:10pt;\">with Python 3.11, QT library 5 and Scintilla</span></p><p align=\"center\"><span style=\" font-size:10pt;\">Version 1.0<br/></span></p></body></html>"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    program_info = QtWidgets.QDialog()
    ui = Ui_program_info()
    ui.setupUi(program_info)
    program_info.show()
    sys.exit(app.exec_())
