# Form implementation generated from reading ui file 'program_info_ui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_program_info(object):
    def setupUi(self, program_info):
        program_info.setObjectName("program_info")
        program_info.resize(541, 466)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:MSql.gif"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        program_info.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(program_info)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=program_info)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=program_info)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.groupBox = QtWidgets.QGroupBox(parent=program_info)
        self.groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.retranslateUi(program_info)
        QtCore.QMetaObject.connectSlotsByName(program_info)

    def retranslateUi(self, program_info):
        _translate = QtCore.QCoreApplication.translate
        program_info.setWindowTitle(_translate("program_info", "About MSql Editor"))
        self.label.setText(_translate("program_info", "<html><body><p align=\"center\"><img src=\"icons:MSql.ico\"/></p><p align=\"center\"><img src=\"icons:python.gif\"/></p><p align=\"center\"><img src=\"icons:qt.gif\"/></p><p align=\"center\"><img src=\"icons:SciTEIco.gif\"/></p></body></html>"))
        self.label_2.setText(_translate("program_info", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">MSql Editor </span><span style=\" font-size:10pt;\">(2023-2025)</span></p><p align=\"center\"><span style=\" font-size:12pt;\">MSql Editor is a SQL text editor for ORACLE environment.</span></p><p align=\"center\"><span style=\" font-size:12pt;\">Developed by </span><span style=\" font-size:12pt; font-weight:600;\">Marco Valaguzza </span></p><p align=\"center\"><span style=\" font-size:12pt;\">with Python 3.13, PyQt6 and QScintilla</span></p><p align=\"center\"><span style=\" font-size:10pt;\">A special thanks to </span><span style=\" font-size:10pt; font-weight:600;\">Filippo Damiani</span><span style=\" font-size:10pt;\"> and </span><span style=\" font-size:10pt; font-weight:600;\">Marco Traini </span></p><p align=\"center\"><span style=\" font-size:10pt;\">for improvements and tests</span></p></body></html>"))
        self.groupBox.setTitle(_translate("program_info", "GNU General Public License"))
        self.label_3.setText(_translate("program_info", "<html><head/><body><p align=\"center\">This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or at your option any later version.</p><p align=\"center\">This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. </p><p align=\"center\">You should have received a copy of the GNU General Public License along with this program. If not, see &lt;<a href=\"https://www.gnu.org/licenses/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.gnu.org/licenses/</span></a>&gt;.</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    program_info = QtWidgets.QDialog()
    ui = Ui_program_info()
    ui.setupUi(program_info)
    program_info.show()
    sys.exit(app.exec())
