# Form implementation generated from reading ui file 'program_info_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_program_info(object):
    def setupUi(self, program_info):
        program_info.setObjectName("program_info")
        program_info.resize(541, 420)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:MSql.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        program_info.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(program_info)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=program_info)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=program_info)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)

        self.retranslateUi(program_info)
        QtCore.QMetaObject.connectSlotsByName(program_info)

    def retranslateUi(self, program_info):
        _translate = QtCore.QCoreApplication.translate
        program_info.setWindowTitle(_translate("program_info", "About MSql Editor"))
        self.label.setText(_translate("program_info", "<html><head/><body><p align=\"center\"><img src=\"icons:MSql.ico\"/></p><p align=\"center\"><img src=\"icons:python.gif\"/></p><p align=\"center\"><img src=\"icons:qt.gif\"/></p><p align=\"center\"><img src=\"icons:SciTEIco.gif\"/></p></body></html>"))
        self.label_2.setText(_translate("program_info", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">MSql Editor</span></p><p align=\"center\"><span style=\" font-size:12pt;\">MSql Editor is a SQL text editor for ORACLE environment.</span></p><p align=\"center\"><span style=\" font-size:14pt;\">Developed by </span><span style=\" font-size:14pt; font-weight:600;\">Marco Valaguzza</span></p><p align=\"center\"><span style=\" font-size:14pt;\">with Python 3.13, PyQt6 and Scintilla</span></p><p align=\"center\"><span style=\" font-size:12pt;\">Version 1.0 (2023-2025)</span><span style=\" font-size:10pt;\"><br/></span></p><p align=\"center\">This program is free software: you can redistribute it and/or modify it under the terms </p><p align=\"center\">of the GNU General Public License as published by the Free Software Foundation, </p><p align=\"center\">either version 3 of the License, or (at your option) any later version.</p><p align=\"center\">This program is distributed in the hope that it will be useful, </p><p align=\"center\">but WITHOUT ANY WARRANTY!!! Without even the implied warranty of </p><p align=\"center\">MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. </p><p align=\"center\">See the GNU General Public License for more details at www.gnu.org/licenses/</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    program_info = QtWidgets.QDialog()
    ui = Ui_program_info()
    ui.setupUi(program_info)
    program_info.show()
    sys.exit(app.exec())
