# Form implementation generated from reading ui file 'select_schema_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_select_schema_window(object):
    def setupUi(self, select_schema_window):
        select_schema_window.setObjectName("select_schema_window")
        select_schema_window.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        select_schema_window.resize(191, 522)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:MSql.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        select_schema_window.setWindowIcon(icon)
        select_schema_window.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(select_schema_window)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.e_find_schema = QtWidgets.QLineEdit(parent=select_schema_window)
        self.e_find_schema.setObjectName("e_find_schema")
        self.gridLayout.addWidget(self.e_find_schema, 0, 0, 1, 1)
        self.b_start = QtWidgets.QPushButton(parent=select_schema_window)
        self.b_start.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons:go.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.b_start.setIcon(icon1)
        self.b_start.setObjectName("b_start")
        self.gridLayout.addWidget(self.b_start, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.e_schema_list = QtWidgets.QListView(parent=select_schema_window)
        self.e_schema_list.setObjectName("e_schema_list")
        self.gridLayout_2.addWidget(self.e_schema_list, 1, 0, 1, 1)
        self.b_confirm_schema = QtWidgets.QPushButton(parent=select_schema_window)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons:database_config.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.b_confirm_schema.setIcon(icon2)
        self.b_confirm_schema.setObjectName("b_confirm_schema")
        self.gridLayout_2.addWidget(self.b_confirm_schema, 2, 0, 1, 1)

        self.retranslateUi(select_schema_window)
        QtCore.QMetaObject.connectSlotsByName(select_schema_window)
        select_schema_window.setTabOrder(self.e_find_schema, self.b_start)
        select_schema_window.setTabOrder(self.b_start, self.e_schema_list)
        select_schema_window.setTabOrder(self.e_schema_list, self.b_confirm_schema)

    def retranslateUi(self, select_schema_window):
        _translate = QtCore.QCoreApplication.translate
        select_schema_window.setWindowTitle(_translate("select_schema_window", "Select schema"))
        self.b_confirm_schema.setText(_translate("select_schema_window", "Select schema"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    select_schema_window = QtWidgets.QDialog()
    ui = Ui_select_schema_window()
    ui.setupUi(select_schema_window)
    select_schema_window.show()
    sys.exit(app.exec())
