# Form implementation generated from reading ui file 'sqlite_viewer_ui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_sqlite_viewer_window(object):
    def setupUi(self, sqlite_viewer_window):
        sqlite_viewer_window.setObjectName("sqlite_viewer_window")
        sqlite_viewer_window.resize(692, 491)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:MSql.gif"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        sqlite_viewer_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=sqlite_viewer_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.b_sqlite_db = QtWidgets.QPushButton(parent=self.centralwidget)
        self.b_sqlite_db.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons:folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.b_sqlite_db.setIcon(icon1)
        self.b_sqlite_db.setObjectName("b_sqlite_db")
        self.gridLayout.addWidget(self.b_sqlite_db, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 0, 1, 1)
        self.o_lst1 = QtWidgets.QTableView(parent=self.centralwidget)
        self.o_lst1.setSortingEnabled(True)
        self.o_lst1.setObjectName("o_lst1")
        self.gridLayout.addWidget(self.o_lst1, 8, 0, 1, 5)
        self.l_label5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.l_label5.setObjectName("l_label5")
        self.gridLayout.addWidget(self.l_label5, 1, 0, 1, 1)
        self.l_label2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.l_label2.setObjectName("l_label2")
        self.gridLayout.addWidget(self.l_label2, 0, 0, 1, 1)
        self.l_label6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.l_label6.setObjectName("l_label6")
        self.gridLayout.addWidget(self.l_label6, 4, 0, 1, 3)
        self.e_where_cond = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_where_cond.sizePolicy().hasHeightForWidth())
        self.e_where_cond.setSizePolicy(sizePolicy)
        self.e_where_cond.setMaximumSize(QtCore.QSize(16777215, 50))
        self.e_where_cond.setObjectName("e_where_cond")
        self.gridLayout.addWidget(self.e_where_cond, 4, 3, 1, 1)
        self.b_start = QtWidgets.QPushButton(parent=self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons:go.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.b_start.setIcon(icon2)
        self.b_start.setObjectName("b_start")
        self.gridLayout.addWidget(self.b_start, 6, 3, 1, 1)
        self.e_table_name = QtWidgets.QComboBox(parent=self.centralwidget)
        self.e_table_name.setEditable(True)
        self.e_table_name.setMaxVisibleItems(20)
        self.e_table_name.setObjectName("e_table_name")
        self.gridLayout.addWidget(self.e_table_name, 1, 3, 1, 1)
        self.e_sqlite_db = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.e_sqlite_db.setClearButtonEnabled(True)
        self.e_sqlite_db.setObjectName("e_sqlite_db")
        self.gridLayout.addWidget(self.e_sqlite_db, 0, 3, 1, 1)
        sqlite_viewer_window.setCentralWidget(self.centralwidget)
        self.l_label5.setBuddy(self.e_table_name)
        self.l_label2.setBuddy(self.e_sqlite_db)
        self.l_label6.setBuddy(self.e_where_cond)

        self.retranslateUi(sqlite_viewer_window)
        self.b_sqlite_db.clicked.connect(sqlite_viewer_window.slot_select_sqlite_db) # type: ignore
        self.b_start.clicked.connect(sqlite_viewer_window.slot_start) # type: ignore
        self.e_sqlite_db.textChanged['QString'].connect(sqlite_viewer_window.slot_elenco_tabelle_sqlite) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(sqlite_viewer_window)
        sqlite_viewer_window.setTabOrder(self.e_sqlite_db, self.b_sqlite_db)
        sqlite_viewer_window.setTabOrder(self.b_sqlite_db, self.b_start)
        sqlite_viewer_window.setTabOrder(self.b_start, self.o_lst1)

    def retranslateUi(self, sqlite_viewer_window):
        _translate = QtCore.QCoreApplication.translate
        sqlite_viewer_window.setWindowTitle(_translate("sqlite_viewer_window", "SQLite viewer"))
        self.label.setText(_translate("sqlite_viewer_window", "Result:"))
        self.l_label5.setText(_translate("sqlite_viewer_window", "Table name:"))
        self.l_label2.setText(_translate("sqlite_viewer_window", "SQLite DB:"))
        self.l_label6.setText(_translate("sqlite_viewer_window", "Where condition:"))
        self.b_start.setText(_translate("sqlite_viewer_window", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sqlite_viewer_window = QtWidgets.QMainWindow()
    ui = Ui_sqlite_viewer_window()
    ui.setupUi(sqlite_viewer_window)
    sqlite_viewer_window.show()
    sys.exit(app.exec())
