# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Exec_job_dialog(object):
    def setupUi(self, Exec_job_dialog):
        Exec_job_dialog.setObjectName("Exec_job_dialog")
        Exec_job_dialog.resize(320, 81)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/MSql.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Exec_job_dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Exec_job_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.progressbar = QtWidgets.QProgressBar(Exec_job_dialog)
        self.progressbar.setProperty("value", 24)
        self.progressbar.setTextVisible(False)
        self.progressbar.setObjectName("progressbar")
        self.gridLayout.addWidget(self.progressbar, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Exec_job_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Exec_job_dialog)
        self.buttonBox.rejected.connect(Exec_job_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Exec_job_dialog)

    def retranslateUi(self, Exec_job_dialog):
        _translate = QtCore.QCoreApplication.translate
        Exec_job_dialog.setWindowTitle(_translate("Exec_job_dialog", "Exec...please wait..."))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Exec_job_dialog = QtWidgets.QDialog()
    ui = Ui_Exec_job_dialog()
    ui.setupUi(Exec_job_dialog)
    Exec_job_dialog.show()
    sys.exit(app.exec_())
